[phases.setup]
nixPkgs = ["python311", "uv"]

[phases.install]
cmds = [
    "uv sync --no-dev --frozen",
]

[start]
cmd = "uv run run_simple_game.py"

[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "uv"
PYTHONUNBUFFERED = "1"
